defaults:
  output_base_dir: "/home/user/experiments_complete"
  base_dir: "/data/pathology/projects/pierpaolo/postdoc/Anaplasia_Classification/virchow/virchow_features/2025-10-08_14_17/"
  labels_csv: "/data/pathology/projects/pierpaolo/postdoc/Anaplasia_Classification/csvs/splits_updated.csv"
  wsi_dir: "/data/pa_cpgarchive/archives/kidney/Wilms_Tumor/Images/"
  patch_size: 224
  n_classes: 2
  epochs: 20
  lr: 1e-4
  batch_size: 1
  penalty_factor: 0.0
  weight_decay: 1e-4
  gmean_threshold: 0.55
  weighted: false
  size: [1280, 512, 256]
  device: "cuda"
  seed: 42
  save_embeddings: true
  mode: "full"
  # --- visualization ---
  draw_topk: 20
  cmap_name: "plasma"
  alpha: 0.6
  convert_to_percentiles: true
  max_size: 8192
  patch_level: 1
  vis_level: -1
  # report_workers: 8  # override if needed; defaults to SLURM_CPUS_PER_TASK or os.cpu_count()

runs:
  baseline:
    name: "anaplasia_mil_baseline"
    
  baseline_weighted:
    name: "anaplasia_mil_weighted_baseline"
    weighted: true

  deep_attention:
    name: "anaplasia_mil_deep_weighted"
    weighted: true
    size: [1280, 2048, 1024, 512, 256]

  only_yes:
    name: "anaplasia_mil_only_yes_weigthed"
    weighted: true
    labels_dir: "/opt/app/user/postdoc/Anaplasia_Classification/csvs/splits_selected_yes.csv"

  deep_yes:
    name: "anaplasia_mil_deep_yes_weighted"
    weighted: true
    size: [1280, 2048, 1024, 512, 256]
    labels_dir: "/opt/app/user/postdoc/Anaplasia_Classification/csvs/splits_selected_yes.csv"

  yes_penalty:
    name: "anaplasia_mil_only_yes_weigthed_p20"
    weighted: true
    penalty_factor: 2.0
    labels_dir: "/opt/app/user/postdoc/Anaplasia_Classification/csvs/splits_selected_yes.csv"
    
